# version: '3.9'
# services:
#   mongodb:
#     image: mongo:latest
#     container_name: mongodb
#     restart: unless-stopped
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db

#   redis-stack:
#     image: redis/redis-stack:latest
#     container_name: redis-stack
#     restart: unless-stopped
#     ports:
#       - "6379:6379"
#       - "8001:8001"
#     volumes:
#       - redis_data:/data

# volumes:
#   mongodb_data:
#     driver: local
#   redis_data:
#     driver: local




version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data:
    driver: local


